### ISSUE TITLE
[General] Create bacalhau-monitoring slack channel

### ISSUE THREAD

**Issue by wdbaruni** [protocol/netops#14]
### What is the goal?
Create public channel in Filecoin that will be used to publish messages about the health of bacalhau network. The name of the channel is `bacalhau-monitoring`

  
### Why do you need this?
One way to have visibility on the health of bacalhau 

  
### What else do we need to know?
It seems I don't have permission to create channels under Filecoin. I don't have a problem creating channels under PL

**DRI:** myself

**Comment by stongo** [comment]
done!

**Comment by wdbaruni** [comment]
Thanks @stongo. I still don't have access to create workflows/webhooks to the channel

**Comment by wdbaruni** [comment]
Opened a new issue #19
